version: '3.3'
services:
  db:
    container_name: submit_db
    restart: on-failure:10
    image: postgres
    environment:
      POSTGRES_USER: submit
      POSTGRES_PASSWORD: ""
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "6000:5432"
  mq:
    container_name: submit_mq
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "4369:4369"
      - "25672:25672"
  submit_cs:
    container_name: submit_cs
    image: thelastpenguin/submit_cs
    build:
      context: .
      dockerfile: ./Dockerfile
    command: "/tmp/submit-cs-startup.sh"
    #command: "tail -f /dev/null"
    #volumes:
    #  - ./build_scripts:/build_scripts
    #  - ./files:/tmp
    ports:
      - "3000:3000"
      - "8080:80"
    depends_on:
      - db
      - mq
    volumes:
     - ./submit:/submit_cs
  submit_worker:
    container_name: submit_worker
    image: thelastpenguin/submit_worker
    build:
      context: .
      dockerfile: ./worker-Dockerfile
    command: "/tmp/worker-startup.sh"
    #command: "tail -f /dev/null"
    #volumes:
    #  - ./build_scripts:/build_scripts
    #  - ./files:/tmp
    #ports:
    #  - "3000:3000"
    depends_on:
      - db
      - mq
      - submit_cs

